// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHHbPTZP6d3ChfsIkT8h5ZhPbBeN3SkOY',
    appId: '1:518784490830:web:09a9ad1f84db3dfc59521f',
    messagingSenderId: '518784490830',
    projectId: 'cravel-sih',
    authDomain: 'cravel-sih.firebaseapp.com',
    storageBucket: 'cravel-sih.appspot.com',
    measurementId: 'G-HETKPNQ64H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmLBwp1uZ7_N40CkWz9JCjfH2YAf1Tv3A',
    appId: '1:518784490830:android:2a2499b33a396ed359521f',
    messagingSenderId: '518784490830',
    projectId: 'cravel-sih',
    storageBucket: 'cravel-sih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGy0IMb6XdkyfnW4UJAAxoyWSAFtT-LFs',
    appId: '1:518784490830:ios:d7e386e214e50f0b59521f',
    messagingSenderId: '518784490830',
    projectId: 'cravel-sih',
    storageBucket: 'cravel-sih.appspot.com',
    iosBundleId: 'com.example.cravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGy0IMb6XdkyfnW4UJAAxoyWSAFtT-LFs',
    appId: '1:518784490830:ios:d7e386e214e50f0b59521f',
    messagingSenderId: '518784490830',
    projectId: 'cravel-sih',
    storageBucket: 'cravel-sih.appspot.com',
    iosBundleId: 'com.example.cravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHHbPTZP6d3ChfsIkT8h5ZhPbBeN3SkOY',
    appId: '1:518784490830:web:7ae15da97cc36afe59521f',
    messagingSenderId: '518784490830',
    projectId: 'cravel-sih',
    authDomain: 'cravel-sih.firebaseapp.com',
    storageBucket: 'cravel-sih.appspot.com',
    measurementId: 'G-RE93MNLCH8',
  );
}
